import os

# Folder where your web files live
WEB_DIR = os.path.join(os.path.dirname(__file__), "web")

# Output header file (in the same folder as this script)
OUT_FILE = os.path.join(os.path.dirname(__file__), "web_assets.h")

# Simple mapping from file extension to MIME type
MIME_TYPES = {
    ".html": "text/html",
    ".htm":  "text/html",
    ".js":   "application/javascript",
    ".css":  "text/css",
    ".json": "application/json",
    ".txt":  "text/plain",
}

def main():
    assets = []

    for root, dirs, files in os.walk(WEB_DIR):
        for fname in files:
            full_path = os.path.join(root, fname)
            rel_path = os.path.relpath(full_path, WEB_DIR).replace("\\", "/")

            # URL path on the ESP (always starts with '/')
            url_path = "/" + rel_path

            _, ext = os.path.splitext(fname)
            mime = MIME_TYPES.get(ext.lower(), "text/plain")

            with open(full_path, "r", encoding="utf-8") as f:
                content = f.read()

            # Escape the content into a raw string literal
            # We'll use R"EOF(... )EOF"
            asset = {
                "url_path": url_path,
                "mime": mime,
                "content": content,
            }
            assets.append(asset)

    # Generate header file
    with open(OUT_FILE, "w", encoding="utf-8") as out:
        out.write("// Auto-generated by embed_web.py. Do not edit by hand.\n")
        out.write("#pragma once\n")
        out.write("#include <Arduino.h>\n\n")
        out.write("struct WebAsset {\n")
        out.write("    const char* path;\n")
        out.write("    const char* contentType;\n")
        out.write("    const char* data;\n")
        out.write("};\n\n")

        # Emit the array
        out.write("static const WebAsset WEB_ASSETS[] = {\n")
        for asset in assets:
            out.write("    {\n")
            out.write(f"        \"{asset['url_path']}\",\n")
            out.write(f"        \"{asset['mime']}\",\n")
            out.write("        R\"EOF(" + asset["content"] + ")EOF\"\n")
            out.write("    },\n")
        out.write("};\n\n")
        out.write("static const size_t WEB_ASSETS_COUNT = sizeof(WEB_ASSETS) / sizeof(WEB_ASSETS[0]);\n\n")

        # Simple lookup function by path
        out.write("inline const WebAsset* find_web_asset(const String& path) {\n")
        out.write("    for (size_t i = 0; i < WEB_ASSETS_COUNT; ++i) {\n")
        out.write("        if (path == WEB_ASSETS[i].path) {\n")
        out.write("            return &WEB_ASSETS[i];\n")
        out.write("        }\n")
        out.write("    }\n")
        out.write("    return nullptr;\n")
        out.write("}\n")

    print(f"Generated {OUT_FILE} with {len(assets)} assets.")

if __name__ == "__main__":
    main()
