// Auto-generated by embed_web.py. Do not edit by hand.
#pragma once
#include <Arduino.h>

struct WebAsset {
    const char* path;
    const char* contentType;
    const char* data;
};

static const WebAsset WEB_ASSETS[] = {
    {
        "/index.html",
        "text/html",
        R"EOF(<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <title>ESP32-C5 WebApp template</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="/style.css">
  <script src="/script.js" defer></script>
</head>
<body>
  <div class="container">
    <h1>ESP32 WebApp</h1>

    <button onclick="sendCmd('HELLO')">Say Hello</button>

    <div id="status"></div>

    <div>
        <h2>Temperature</h2>
        <div id="temperature">-- °C</div>
    </div>


    <footer>ESP32-C5 WebApp Template</footer>
  </div>

</body>
</html>
)EOF"
    },
    {
        "/script.js",
        "application/javascript",
        R"EOF(

function sendCmd(param) {

  console.log('A enviar comando "' + param + '"...');

  fetch("/path", {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded"
    },
    body: "param=" + encodeURIComponent(param)
  })
    .then(response => response.text())
    .then(text => {
      console.log(text);
      document.getElementById("status").innerText = text;
    })
    .catch(err => {
      console.log("Erro ao comunicar com o ESP32: " + err);
    });
}


function updateTemperature() {
    fetch("/path")
        .then(response => response.json())
        .then(data => {
            const tempEl = document.getElementById("temperature");
            tempEl.textContent = data.temperature.toFixed(2) + " °C";
        })
        .catch(err => {
            console.error("Temperature read error:", err);
        });
}


setInterval(updateTemperature, 1000);
)EOF"
    },
    {
        "/style.css",
        "text/css",
        R"EOF(/* ------------------------------
   Global Layout
--------------------------------*/
body {
    margin: 0;
    padding: 0;
    font-family: Arial, sans-serif;
    background: #f0f2f5;
    color: #222;
    display: flex;
    justify-content: center;
    align-items: flex-start;
    min-height: 100vh;
}

/* ------------------------------
   Main container/card
--------------------------------*/
.container {
    background: #fff;
    width: 90%;
    max-width: 480px;
    padding: 20px 24px;
    margin-top: 40px;
    border-radius: 12px;
    box-shadow: 0 4px 16px rgba(0,0,0,0.12);
}

/* ------------------------------
   Title
--------------------------------*/
h1 {
    text-align: center;
    font-size: 1.5rem;
    margin-bottom: 24px;
    color: #333;
}

/* ------------------------------
   Buttons
--------------------------------*/
button {
    width: 100%;
    padding: 12px;
    margin: 8px 0;
    border: none;
    border-radius: 8px;
    background: #0078ff;
    color: white;
    font-size: 1rem;
    cursor: pointer;
    transition: background 0.25s ease, transform 0.15s ease;
}

button:hover {
    background: #005fcc;
    transform: translateY(-2px);
}

button:active {
    transform: translateY(0);
}

/* Variant if needed */
button.secondary {
    background: #e0e0e0;
    color: #222;
}

button.secondary:hover {
    background: #c8c8c8;
}

/* ------------------------------
   Status bar
--------------------------------*/
#status {
    margin-top: 16px;
    padding: 12px;
    background: #eef3ff;
    border-left: 4px solid #0078ff;
    border-radius: 6px;
    font-size: 0.95rem;
    min-height: 20px;
}

/* When showing an error */
#status.error {
    background: #ffecec;
    border-left-color: #e60000;
}

/* ------------------------------
   Footer small text
--------------------------------*/
footer {
    text-align: center;
    margin-top: 24px;
    font-size: 0.8rem;
    color: #666;
}
)EOF"
    },
};

static const size_t WEB_ASSETS_COUNT = sizeof(WEB_ASSETS) / sizeof(WEB_ASSETS[0]);

inline const WebAsset* find_web_asset(const String& path) {
    for (size_t i = 0; i < WEB_ASSETS_COUNT; ++i) {
        if (path == WEB_ASSETS[i].path) {
            return &WEB_ASSETS[i];
        }
    }
    return nullptr;
}
